# Generated by Django 6.0.7 on 2026-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transactionimage_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('food', 'Food'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('clothing', 'Clothing'), ('housing', 'Housing'), ('savings', 'Savings'), ('investment', 'Investment'), ('miscellaneous', 'Miscellaneous'), ('tax', 'Tax')], max_length=50),
        ),
    ]
